version: '0.1'
services:
  app:
    build: .
    container_name: spring_demo_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db  # Service name as hostname
      DB_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword

  db:
    image: postgres:15
    container_name: demo_postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: